import React, { createContext, useContext, useMemo, useState, type ReactNode } from 'react'

export type SupportedLanguage = 'fr' | 'en'

// eslint-disable-next-line react-refresh/only-export-components
export const translations = {
  fr: {
    nav: {
      home: 'Accueil',
      nosProduits: 'Nos Produits',
      apropos: 'À propos',
      contact: 'Contact',
      connexion: 'Connexion',
      inscription: 'Inscription',
      menuHome: 'Accueil',
      menuNosProduits: 'Nos Produits',
      menuApropos: 'À Propos',
      menuContact: 'Contact',
      menuConnexion: 'Connexion',
    },
    home: {
      languageLabel: 'Langue',
      languageFr: 'Français',
      languageEn: 'Anglais',
      heroTitle: 'Trouvez vos chips idéals chez nous',
      heroSubtitle: 'Avec BIKOAN SARL, explorez nos produits artisanaux préparés avec soin.',
      products: 'Nos Produits',
      distributorsTitle: 'Nos Distributeurs',
      distributorsText: 'Notre réseau de distributeurs garantit une couverture étendue pour la livraison de nos produits partout.',
      entrepriseTitle: "Présentation de l'Entreprise",
      entrepriseText: "Un aperçu rapide de notre mission, nos valeurs et notre engagement envers la qualité.",
      preparationTitle: 'Préparation',
      preparationText: "Apprenez comment nos produits sont préparés, de la sélection des ingrédients à l'emballage final.",
      whyChooseTitle: 'Pourquoi nous choisir ?',
      localisationTitle: 'Notre Localisation',
      viewMore: 'Voir plus',
      addressHeadline: 'Notre adresse — utilisez cette localisation pour nous trouver',
    },
    productCard: {
      view: 'Voir le produit',
      priceLabel: 'FCFA',
    },
    productDetail: {
      description: 'Description',
      notFound: 'Produit non trouvé',
      additionalInfo: 'Informations supplémentaires',
      tel: 'Tél',
      phone: '+237 695 64 01 44',
      contactPhone: 'Tél :',
      contactEmailLabel: 'Contactez-nous par email :',
      infoTitle: 'Informations supplémentaires',
    },
    localisation: {
      title: 'Entreprise Bikoan Sarl — Localisation',
    },
    prepare: {
      chips: {
        saltyLabel: 'Chips salées',
        sweetLabel: 'Chips sucrées',
        headingSalty: 'Comment faire des chips salées',
        headingSweet: 'Comment faire des chips sucrées',
        subheading: 'Croustillantes, faciles à préparer à la maison.',
        saltySteps: [
          { title: 'Éplucher', description: "Épluchez les plantains ou pommes de terre et rincez-les à l'eau claire." },
          { title: 'Trancher', description: "Coupez en fines rondelles régulières à l'aide d'un couteau ou d'une mandoline." },
          { title: 'Assaisonner', description: 'Saupoudrez de sel fin et mélangez délicatement pour bien répartir.' },
          { title: "Chauffer l'huile", description: "Faites chauffer l'huile dans une poêle profonde à feu moyen-vif." },
          { title: 'Frire', description: "Plongez les tranches dans l'huile chaude et faites frire jusqu'à ce qu'elles soient dorées et croustillantes." },
          { title: 'Égoutter', description: "Retirez et posez sur du papier absorbant pour enlever l'excès d'huile." },
        ],
        sweetSteps: [
          { title: 'Éplucher', description: 'Épluchez des plantains bien mûrs et rincez-les.' },
          { title: 'Trancher', description: 'Coupez en fines rondelles ou en lamelles allongées.' },
          { title: "Chauffer l'huile", description: "Faites chauffer l'huile à feu moyen dans une poêle profonde." },
          { title: 'Frire', description: "Faites frire les tranches jusqu'à obtenir une belle couleur dorée." },
          { title: 'Égoutter', description: "Posez sur du papier absorbant pour retirer l'excès d'huile." },
          { title: 'Saupoudrer', description: "Ajoutez un peu de sucre en poudre ou du miel pendant que c'est encore chaud." },
        ],
      },
      sesame: {
        heading: 'Comment faire des croquettes de sésame',
        subheading: 'Une recette simple, croustillante et pleine de saveur.',
        steps: [
          { title: 'Préparer les graines', description: "Triez les graines de sésame pour enlever les impuretés, puis rincez-les rapidement et laissez-les égoutter." },
          { title: 'Torréfier', description: "Faites griller les graines à feu doux dans une poêle sèche, en remuant constamment jusqu'à ce qu'elles deviennent dorées et parfumées." },
          { title: 'Préparer le sirop', description: "Dans une casserole, faites fondre du sucre avec un peu d'eau à feu moyen jusqu'à obtenir un caramel léger." },
          { title: 'Mélanger', description: 'Ajoutez les graines de sésame torréfiées au caramel chaud et mélangez rapidement pour bien enrober.' },
          { title: 'Étaler', description: 'Versez le mélange sur une surface huilée ou du papier sulfurisé, puis aplatissez avec un rouleau ou une spatule huilée.' },
          { title: 'Découper', description: 'Avant que ça refroidisse complètement, découpez en morceaux ou en barres de la taille souhaitée.' },
          { title: 'Laisser refroidir', description: 'Laissez durcir complètement à température ambiante avant de démouler et servir.' },
        ],
      },
      stepPrefix: 'Étape',
      chipsTitle: 'Nos Chips',
      chipsDesc: 'Découvrez comment nos chips croustillantes sont préparées avec soin.',
      sesameTitle: 'Notre Sésame',
      sesameDesc: 'Apprenez comment nos croquettes de sésame sont fabriquées.',
      noVideoConfigured: 'Vidéo bientôt disponible.',
    },
    app: {
      pageNotFound: 'Page non trouvée',
    },
    footer: {
      description: "BIKOAN SARL est une entreprise camerounaise spécialisée dans la fabrication et la vente de chips artisanales et de croquettes de sésame de qualité supérieure.",
      pages: 'NOS PAGES',
      legal: 'LÉGAL',
      followUs: 'CONTACT',
      sendMail: 'Envoyez-nous un mail',
      rights: "© 2026 BIKOAN SARL. Tous droits réservés.",
      condition: 'Conditions générales',
      mention: 'Mentions légales',
      confidentialite: 'Confidentialité',
    },
    contact: {
      title: 'CONTACTEZ-NOUS',
      name: 'Nom',
      email: 'Email',
      message: 'Message',
      telephone: 'Téléphone',
      namePlaceholder: 'Votre nom complet',
      emailPlaceholder: 'Votre adresse e-mail',
      messagePlaceholder: 'Expliquez-nous comment nous pouvons vous aider...',
      submit: 'Envoyer le message',
      answer: 'Nous vous répondrons dans les plus brefs délais.',
    },
    connexion: {
      title: 'CONNEXION',
      email: 'E-mail',
      password: 'Mot de passe',
      emailPlaceholder: 'Votre adresse e-mail',
      passwordPlaceholder: 'Votre mot de passe',
      login: 'Se connecter',
      noAccount: "Vous n'avez pas de compte ?",
      signup: 'Inscrivez-vous ici',
      forgotPassword: 'Mot de passe oublié ?',
      clickHere: 'Cliquez ici',
      thanks: 'Merci de votre confiance envers BIKOAN SARL.',
    },
    inscription: {
      title: 'Créer un compte',
      name: 'Nom complet',
      email: 'Email',
      password: 'Mot de passe',
      role: 'Je suis',
      roleOption1: 'Agent commercial (Acheteur / Revendeur)',
      roleOption2: 'Entrepreneur (Professionnel)',
      namePlaceholder: 'Entrez votre nom complet',
      emailPlaceholder: 'Entrez votre adresse e-mail',
      passwordPlaceholder: 'Créez un mot de passe',
      signup: "S'inscrire",
      selectRole: 'Choisissez votre rôle',
    },
    apropos: {
      title: "À propos de BIKOAN SARL",
      paragraph1: "BIKOAN SARL est une entreprise camerounaise engagée dans la fabrication artisanale de chips et de croquettes de sésame. Nous sélectionnons des ingrédients locaux de qualité pour vous offrir des produits savoureux, sains et authentiques.",
      paragraph2: "Que vous soyez distributeur, revendeur ou consommateur, nous proposons des produits de première qualité avec une distribution fiable et rapide à travers tout le Cameroun et au-delà.",
    },
    confidentialite: {
      title: 'Politique de confidentialité',
      intro: "BIKOAN SARL respecte votre vie privée. Aucune donnée personnelle ne sera vendue ou transmise à des tiers.",
      usage: "Vos informations sont utilisées uniquement pour améliorer votre expérience sur notre site et traiter vos demandes.",
      collectTitle: 'Collecte de données',
      collectText: "Les informations collectées (nom, email, téléphone) sont utilisées uniquement pour répondre à vos demandes de contact ou d'inscription. Elles ne sont jamais partagées sans votre consentement.",
      cookieTitle: 'Cookies',
      cookieText: "Ce site utilise des cookies techniques pour améliorer l'expérience utilisateur. Aucun cookie de traçage publicitaire n'est utilisé.",
      rightsTitle: 'Vos droits',
      rightsText: "Conformément à la loi, vous pouvez demander à consulter, modifier ou supprimer vos données personnelles à tout moment en nous contactant.",
    },
    condition: {
      title: "Conditions Générales d'Utilisation",
      intro: "Bienvenue sur le site de BIKOAN SARL. En utilisant ce site, vous acceptez les présentes conditions générales d'utilisation.",
      item1Title: '1. Objet du site',
      item1Text: "Ce site a pour objet de présenter les produits de BIKOAN SARL (chips artisanales, croquettes de sésame) et de permettre aux visiteurs de prendre contact avec nous.",
      item2Title: '2. Utilisation du service',
      item2Text: "Toute utilisation abusive, frauduleuse ou contraire aux bonnes mœurs de ce site pourra entraîner des poursuites légales.",
      item3Title: '3. Propriété intellectuelle',
      item3Text: "Tous les contenus présents sur ce site (textes, images, logo) sont la propriété exclusive de BIKOAN SARL et ne peuvent être reproduits sans autorisation écrite.",
    },
    mention: {
      title: 'Mentions légales',
      text: "BIKOAN SARL — Entreprise camerounaise de fabrication de snacks artisanaux. Les informations présentées sur ce site sont fournies à titre informatif. Toute reproduction ou diffusion est interdite sans autorisation préalable de BIKOAN SARL.",
    },
    nosproduit: {
      description: 'Découvrez nos chips croustillantes et nos croquettes de sésame premium, préparées avec soin pour un goût authentique.',
      homeIntro: "Explorez notre gamme de chips artisanales et de croquettes de sésame soigneusement sélectionnées, prêtes à régaler vos clients.",
    },
    entreprise: {
      introText: "BIKOAN SARL est une entreprise locale engagée à produire des chips et des croquettes de sésame de première qualité. Notre équipe sélectionne des ingrédients premium et assure une distribution fiable à travers tout le pays.",
      feature1Title: 'Qualité locale',
      feature1Desc: 'Ingrédients sélectionnés avec soin pour un goût authentique et naturel.',
      feature2Title: 'Expertise artisanale',
      feature2Desc: 'Un savoir-faire traditionnel adapté à une production moderne et hygiénique.',
      feature3Title: 'Distribution fiable',
      feature3Desc: 'Nos distributeurs assurent une livraison rapide et sécurisée partout.',
    },
    distributeurs: {
      title: 'Nos Distributeurs',
    },
    whyChooseUs: {
      sectionTitle: 'Pourquoi nous choisir ?',
      mainTitle: 'La qualité au cœur de chacun de nos produits',
      mainDesc: "Chez BIKOAN SARL, nous mettons notre expertise au service de la fabrication de snacks savoureux, sains et de qualité afin d'offrir une expérience unique à chacun de nos consommateurs.",
      item1Title: 'Produits Naturels',
      item1Desc: 'Nos snacks sont préparés avec des ingrédients soigneusement sélectionnés pour garantir un goût authentique et une qualité exceptionnelle.',
      item2Title: 'Qualité Garantie',
      item2Desc: 'Chaque produit est soumis à un contrôle qualité rigoureux avant sa mise sur le marché.',
      item3Title: 'Livraison Rapide',
      item3Desc: "Nous assurons une distribution rapide afin que nos produits arrivent toujours frais chez nos partenaires et clients.",
      item4Title: 'Savoir-Faire',
      item4Desc: "Notre expérience dans la transformation alimentaire nous permet d'offrir des produits appréciés pour leur saveur et leur qualité.",
    },
  },

  // ─────────────────────────────────────────────────────────────
  //  ENGLISH
  // ─────────────────────────────────────────────────────────────
  en: {
    nav: {
      home: 'Home',
      nosProduits: 'Our Products',
      apropos: 'About',
      contact: 'Contact',
      connexion: 'Login',
      inscription: 'Sign Up',
      menuHome: 'Home',
      menuNosProduits: 'Our Products',
      menuApropos: 'About',
      menuContact: 'Contact',
      menuConnexion: 'Login',
    },
    home: {
      languageLabel: 'Language',
      languageFr: 'French',
      languageEn: 'English',
      heroTitle: 'Find your ideal chips with us',
      heroSubtitle: 'With BIKOAN SARL, discover our handcrafted products prepared with care.',
      products: 'Our Products',
      distributorsTitle: 'Our Distributors',
      distributorsText: 'Our distributor network ensures wide coverage for the delivery of our products everywhere.',
      entrepriseTitle: 'Company Overview',
      entrepriseText: 'A quick look at our mission, values and commitment to quality.',
      preparationTitle: 'Preparation',
      preparationText: 'Learn how our products are prepared, from ingredient selection to final packaging.',
      whyChooseTitle: 'Why choose us?',
      localisationTitle: 'Our Location',
      viewMore: 'See more',
      addressHeadline: 'Our address — use this location to find us',
    },
    productCard: {
      view: 'View product',
      priceLabel: 'FCFA',
    },
    productDetail: {
      description: 'Description',
      notFound: 'Product not found',
      additionalInfo: 'Additional information',
      tel: 'Phone',
      phone: '+237 695 64 01 44',
      contactPhone: 'Phone:',
      contactEmailLabel: 'Contact us by email:',
      infoTitle: 'Additional information',
    },
    localisation: {
      title: 'Bikoan SARL — Location',
    },
    prepare: {
      chips: {
        saltyLabel: 'Salty chips',
        sweetLabel: 'Sweet chips',
        headingSalty: 'How to make salty chips',
        headingSweet: 'How to make sweet chips',
        subheading: 'Crispy and easy to prepare at home.',
        saltySteps: [
          { title: 'Peel', description: 'Peel the plantains or potatoes and rinse them in clean water.' },
          { title: 'Slice', description: 'Cut into thin, regular rounds using a knife or mandoline.' },
          { title: 'Season', description: 'Sprinkle with fine salt and mix gently to distribute evenly.' },
          { title: 'Heat oil', description: 'Heat the oil in a deep pan over medium-high heat.' },
          { title: 'Fry', description: 'Drop the slices into the hot oil and fry until golden and crispy.' },
          { title: 'Drain', description: 'Remove and place on paper towels to absorb excess oil.' },
        ],
        sweetSteps: [
          { title: 'Peel', description: 'Peel ripe plantains and rinse them.' },
          { title: 'Slice', description: 'Cut into thin rounds or long slices.' },
          { title: 'Heat oil', description: 'Heat the oil over medium heat in a deep pan.' },
          { title: 'Fry', description: 'Fry the slices until they turn a beautiful golden color.' },
          { title: 'Drain', description: 'Place on paper towels to remove excess oil.' },
          { title: 'Sprinkle', description: 'Add a little powdered sugar or honey while still warm.' },
        ],
      },
      sesame: {
        heading: 'How to make sesame croquettes',
        subheading: 'A simple, crispy and flavourful recipe.',
        steps: [
          { title: 'Prepare the seeds', description: 'Sort the sesame seeds to remove impurities, rinse quickly and let drain.' },
          { title: 'Toast', description: 'Toast the seeds over low heat in a dry pan, stirring constantly until golden and fragrant.' },
          { title: 'Prepare the syrup', description: 'In a saucepan, melt sugar with a little water over medium heat until you get a light caramel.' },
          { title: 'Mix', description: 'Add the toasted sesame seeds to the hot caramel and stir quickly to coat well.' },
          { title: 'Spread', description: 'Pour the mixture onto an oiled surface or baking paper, then flatten with an oiled roller or spatula.' },
          { title: 'Cut', description: 'Before it cools completely, cut into pieces or bars of the desired size.' },
          { title: 'Let cool', description: 'Let harden completely at room temperature before unmoulding and serving.' },
        ],
      },
      stepPrefix: 'Step',
      chipsTitle: 'Our Chips',
      chipsDesc: 'Discover how our crispy chips are carefully prepared.',
      sesameTitle: 'Our Sesame',
      sesameDesc: 'Learn how our sesame croquettes are crafted.',
      noVideoConfigured: 'Video coming soon.',
    },
    app: {
      pageNotFound: 'Page not found',
    },
    footer: {
      description: 'BIKOAN SARL is a Cameroonian company specialising in the artisanal production and sale of high-quality chips and sesame croquettes.',
      pages: 'OUR PAGES',
      legal: 'LEGAL',
      followUs: 'CONTACT',
      sendMail: 'Send us an email',
      rights: '© 2026 BIKOAN SARL. All rights reserved.',
      condition: 'Terms & Conditions',
      mention: 'Legal Notice',
      confidentialite: 'Privacy Policy',
    },
    contact: {
      title: 'CONTACT US',
      name: 'Name',
      email: 'Email',
      message: 'Message',
      telephone: 'Phone',
      namePlaceholder: 'Your full name',
      emailPlaceholder: 'Your email address',
      messagePlaceholder: 'Tell us how we can help you...',
      submit: 'Send message',
      answer: 'We will get back to you as soon as possible.',
    },
    connexion: {
      title: 'LOGIN',
      email: 'E-mail',
      password: 'Password',
      emailPlaceholder: 'Your email address',
      passwordPlaceholder: 'Your password',
      login: 'Log in',
      noAccount: "Don't have an account?",
      signup: 'Sign up here',
      forgotPassword: 'Forgot password?',
      clickHere: 'Click here',
      thanks: 'Thank you for trusting BIKOAN SARL.',
    },
    inscription: {
      title: 'Create an account',
      name: 'Full name',
      email: 'Email',
      password: 'Password',
      role: 'I am a',
      roleOption1: 'Sales agent (Buyer / Reseller)',
      roleOption2: 'Entrepreneur (Professional)',
      namePlaceholder: 'Enter your full name',
      emailPlaceholder: 'Enter your email address',
      passwordPlaceholder: 'Create a password',
      signup: 'Sign up',
      selectRole: 'Choose your role',
    },
    apropos: {
      title: 'About BIKOAN SARL',
      paragraph1: 'BIKOAN SARL is a Cameroonian company committed to the artisanal production of chips and sesame croquettes. We select quality local ingredients to offer you flavourful, healthy and authentic products.',
      paragraph2: 'Whether you are a distributor, reseller or consumer, we offer top-quality products with reliable and fast distribution across Cameroon and beyond.',
    },
    confidentialite: {
      title: 'Privacy Policy',
      intro: 'BIKOAN SARL respects your privacy. No personal data will ever be sold or shared with third parties.',
      usage: 'Your information is used solely to improve your experience on our site and to process your requests.',
      collectTitle: 'Data collection',
      collectText: 'Information collected (name, email, phone) is used only to respond to your contact or registration requests. It is never shared without your consent.',
      cookieTitle: 'Cookies',
      cookieText: 'This site uses technical cookies to improve the user experience. No advertising tracking cookies are used.',
      rightsTitle: 'Your rights',
      rightsText: 'In accordance with the law, you may request to view, modify or delete your personal data at any time by contacting us.',
    },
    condition: {
      title: 'Terms of Use',
      intro: 'Welcome to the BIKOAN SARL website. By using this site, you agree to these terms of use.',
      item1Title: '1. Purpose of the site',
      item1Text: 'This site presents the products of BIKOAN SARL (artisanal chips, sesame croquettes) and allows visitors to get in touch with us.',
      item2Title: '2. Use of service',
      item2Text: 'Any abusive, fraudulent or improper use of this site may result in legal action.',
      item3Title: '3. Intellectual property',
      item3Text: 'All content on this site (text, images, logo) is the exclusive property of BIKOAN SARL and may not be reproduced without written authorisation.',
    },
    mention: {
      title: 'Legal Notice',
      text: 'BIKOAN SARL — Cameroonian artisanal snack manufacturer. The information on this site is provided for informational purposes only. Any reproduction or distribution is prohibited without prior written authorisation from BIKOAN SARL.',
    },
    nosproduit: {
      description: 'Discover our crispy chips and premium sesame croquettes, carefully prepared for an authentic taste.',
      homeIntro: 'Explore our range of artisanal chips and carefully selected sesame croquettes, ready to delight your customers.',
    },
    entreprise: {
      introText: 'BIKOAN SARL is a local company committed to producing high-quality chips and sesame croquettes. Our team selects premium ingredients and ensures reliable distribution across the country.',
      feature1Title: 'Local quality',
      feature1Desc: 'Carefully selected ingredients for an authentic and natural taste.',
      feature2Title: 'Artisanal expertise',
      feature2Desc: 'Traditional know-how combined with modern, hygienic production.',
      feature3Title: 'Reliable distribution',
      feature3Desc: 'Our distributors ensure fast and secure delivery everywhere.',
    },
    distributeurs: {
      title: 'Our Distributors',
    },
    whyChooseUs: {
      sectionTitle: 'Why choose us?',
      mainTitle: 'Quality at the heart of every product',
      mainDesc: 'At BIKOAN SARL, we bring our expertise to crafting delicious, healthy and high-quality snacks to deliver a unique experience to every consumer.',
      item1Title: 'Natural Products',
      item1Desc: 'Our snacks are made with carefully selected ingredients to ensure authentic taste and exceptional quality.',
      item2Title: 'Guaranteed Quality',
      item2Desc: 'Every product undergoes rigorous quality control before reaching the market.',
      item3Title: 'Fast Delivery',
      item3Desc: 'We ensure fast distribution so our products always arrive fresh to our partners and customers.',
      item4Title: 'Expertise',
      item4Desc: 'Our experience in food processing allows us to offer products valued for their flavour and quality.',
    },
  },
}

type LanguageContextValue = {
  language: SupportedLanguage
  setLanguage: (language: SupportedLanguage) => void
  t: typeof translations['fr']
}

const LanguageContext = createContext<LanguageContextValue | undefined>(undefined)

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<SupportedLanguage>('fr')
  const t = useMemo(() => translations[language], [language])

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  )
}

// eslint-disable-next-line react-refresh/only-export-components
export const useLanguage = (): LanguageContextValue => {
  const context = useContext(LanguageContext)
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider')
  }
  return context
}
